name: Build Executable

# Trigger the workflow on push or pull request events to the 'main' branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs for the workflow
jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version (3.x)

      # Step 3: Install required dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          # You can install any other dependencies your project might require (e.g., `openpyxl`, `msoffcrypto`)
          pip install openpyxl msoffcrypto

      # Step 4: Build the Python project as an executable
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile src/main.py  # Replace with the entry point of your application
          ls -al dist/  # Verify that the executable was created in the 'dist' folder

      # Step 5: Upload the built executable as an artifact
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: dist/main  # Path to the built executable (adjust based on your PyInstaller setup)
